version: "3.9"

services:
  otp-graph-builder:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/app/external
    environment:
      - ACCESS_KEY_ID=${ACCESS_KEY_ID}
      - SECRET_ACCESS_KEY=${SECRET_ACCESS_KEY}
